"""FastAPI routes for the Chroniclon wiki.

Mounted at /api/chronicle/* by main.py.
"""
import asyncio
import json
import re
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sse_starlette.sse import EventSourceResponse

from config import CHRONICLON_DIR
from chroniclon import store
from chroniclon import control_stream
from chroniclon.models import WikiArticle
from chroniclon.regen import stream_regen


router = APIRouter(prefix="/api/chronicle", tags=["chronicle"])


# --------------------------------------------------------------------------- #
#  Stats / index                                                              #
# --------------------------------------------------------------------------- #

@router.get("/stats")
async def stats() -> dict:
    eras = store.list_eras()
    return {
        "article_count": store.article_count(),
        "total_words": store.total_word_count(),
        "era_count": len(eras),
        "current_era": eras[-1].name if eras else None,
        "linguistic_eras": len(store.list_linguistic_eras()),
        "contributor_count": store.contributor_count(),
    }


@router.get("/articles")
async def list_articles(
    era_id: str | None = None,
    kind: str | None = None,
    limit: int = Query(default=50, le=500),
    offset: int = Query(default=0, ge=0),
) -> dict:
    return {"items": store.list_articles(era_id=era_id, kind=kind, limit=limit, offset=offset)}


@router.get("/articles/{slug}")
async def get_article(slug: str) -> WikiArticle:
    a = store.load_article_by_slug(slug)
    if not a:
        raise HTTPException(404, f"article not found: {slug}")
    return a


@router.get("/eras")
async def list_eras() -> dict:
    return {"items": [e.model_dump() for e in store.list_eras()]}


@router.get("/audio/{slug}")
async def get_audio(slug: str):
    """Serve a rendered TTS chapter for an article. The audio is rendered by
    `python -m chroniclon.audio_chapter --slug <slug>` and saved to
    data/chroniclon/audio/<slug>.mp3."""
    safe = re.sub(r"[^a-z0-9\-]", "", slug.lower())
    audio_path = Path(CHRONICLON_DIR) / "audio" / f"{safe}.mp3"
    if not audio_path.exists():
        raise HTTPException(404, f"no audio rendered for slug: {safe}")
    return FileResponse(str(audio_path), media_type="audio/mpeg", filename=f"{safe}.mp3")


def _find_era_by_id(era_id: str):
    for e in store.list_eras():
        if e.era_id == era_id:
            return e
    return None


@router.get("/images/{slug}")
async def get_article_image(slug: str):
    """Serve the rendered hero image for an article. Generated by the
    auto-render hook in canon_agent or via POST /images/render."""
    safe = re.sub(r"[^a-z0-9\-]", "", (slug or "").lower())
    img_path = Path(CHRONICLON_DIR) / "images" / f"{safe}.webp"
    if not img_path.exists():
        raise HTTPException(404, f"no image rendered for slug: {safe}")
    return FileResponse(str(img_path), media_type="image/webp", filename=f"{safe}.webp")


class RenderImageRequest(BaseModel):
    slug: str


@router.post("/images/render")
async def render_image(req: RenderImageRequest) -> dict:
    """On-demand article hero image render. Used by the MCP bridge and the
    retrofit CLI. Re-runs always overwrite the existing webp."""
    from chroniclon.illustrations import is_configured as _img_configured
    from chroniclon.illustrations import render_article_image

    if not _img_configured():
        raise HTTPException(503, "IMAGE_API_KEY not set — image rendering disabled")
    slug = re.sub(r"[^a-z0-9\-]", "", (req.slug or "").lower())
    if not slug:
        raise HTTPException(400, "slug required")
    article = store.load_article_by_slug(slug)
    if article is None:
        raise HTTPException(404, f"article not found: {slug}")
    era = _find_era_by_id(article.era_id)
    art_style = (getattr(era, "art_style", "") or "") if era else ""
    result = await render_article_image(
        slug=slug,
        kind=article.kind,
        title=article.title,
        era_art_style=art_style,
        character=None,  # MCP/CLI path — no character context yet
    )
    article.illustration_url = result["url"]
    store.save_article(article)
    return result


class RenderAudioRequest(BaseModel):
    slug: str


@router.post("/audio/render")
async def render_audio(req: RenderAudioRequest) -> dict:
    """On-demand audio render for an existing article — used by the MCP bridge
    so hermes-agent can voice an article without invoking the CLI. Idempotent;
    re-running overwrites the existing mp3.
    """
    from chroniclon.voices import is_configured as _tts_configured
    from chroniclon.audio_chapter import render_chapter

    if not _tts_configured():
        raise HTTPException(503, "TTS not configured — set TTS_PROVIDER and the matching API key")
    slug = re.sub(r"[^a-z0-9\-]", "", (req.slug or "").lower())
    if not slug:
        raise HTTPException(400, "slug required")
    if not store.load_article_by_slug(slug):
        raise HTTPException(404, f"article not found: {slug}")
    return await render_chapter(slug)


@router.get("/lexicon")
async def lexicon() -> dict:
    return {"items": [le.model_dump() for le in store.list_linguistic_eras()]}


# --------------------------------------------------------------------------- #
#  Audience contribution                                                       #
# --------------------------------------------------------------------------- #

class SubmissionRequest(BaseModel):
    contributor_handle: str
    seed_text: str


@router.post("/submit")
async def submit(req: SubmissionRequest) -> dict:
    import uuid
    from chroniclon.models import CanonSubmission

    handle = (req.contributor_handle or "anonymous").strip()[:64]
    seed = (req.seed_text or "").strip()
    if not seed:
        raise HTTPException(400, "seed_text required")
    if len(seed) > 600:
        raise HTTPException(400, "seed_text too long (max 600 chars)")

    sub = CanonSubmission(
        submission_id=f"sub_{uuid.uuid4().hex[:12]}",
        contributor_handle=handle,
        seed_text=seed,
    )
    store.save_submission(sub)
    return {"submission_id": sub.submission_id, "status": "pending"}


@router.get("/submissions")
async def list_submissions(status: str | None = None) -> dict:
    return {"items": [s.model_dump() for s in store.list_submissions(status)]}


# --------------------------------------------------------------------------- #
#  Live regen — demo flow that proves the engine works on any seed             #
# --------------------------------------------------------------------------- #

class RegenRequest(BaseModel):
    seed: str
    days: int = 5
    # "kimi" makes Kimi K2.6 write the article bodies (visible in the demo,
    # required for the Kimi track). "nous" stays cheap. Anything else falls
    # through to the regen default.
    provider: str | None = None


# --------------------------------------------------------------------------- #
#  Canon Control Room                                                          #
# --------------------------------------------------------------------------- #

@router.get("/control/backlog")
async def control_backlog(limit: int = Query(default=50, ge=1, le=80)) -> dict:
    """Recent canonization phase events. Frontend hits this on first load
    before subscribing to the SSE stream so the page is alive immediately."""
    return {"items": control_stream.backlog_snapshot(limit=limit)}


@router.get("/control/stream")
async def control_event_stream():
    """SSE feed of canonization phase events for the Control Room.

    Each event is a JSON blob with at least: ts, phase, pipeline_id, model,
    stage. Phases include: decision_started, decision_complete, skipped,
    writing_started, writing_complete, antislop_complete, factcheck_complete,
    revision_started, crosslinks_complete, published, audio_started,
    audio_complete, audio_failed.
    """
    async def gen():
        q = await control_stream.subscribe()
        try:
            while True:
                try:
                    event = await asyncio.wait_for(q.get(), timeout=15.0)
                except asyncio.TimeoutError:
                    # Heartbeat keeps proxies / browsers from closing the connection.
                    yield "event: ping\ndata: {}\n\n"
                    continue
                yield f"event: phase\ndata: {json.dumps(event)}\n\n"
        finally:
            control_stream.unsubscribe(q)

    return EventSourceResponse(gen())


@router.post("/regen/stream")
async def regen_stream(req: RegenRequest):
    seed = (req.seed or "").strip()
    if not seed:
        raise HTTPException(400, "seed required")
    if len(seed) > 600:
        raise HTTPException(400, "seed too long (max 600 chars)")
    days = max(1, min(int(req.days or 5), 12))
    provider = (req.provider or "").strip().lower()
    if provider not in ("kimi", "nous"):
        provider = "kimi"  # default: showcase Kimi for the Kimi track

    async def gen():
        async for chunk in stream_regen(seed, days, writer_provider=provider):
            # sse-starlette accepts dicts or already-formatted strings; we hand it our raw frames
            yield chunk

    return EventSourceResponse(gen())
